### ISSUE TITLE
Documentation link goes to a link farm 

### ISSUE THREAD

**Issue by tillberg** [saintfish/chardet#4]
The README links to http://go.pkgdoc.org/github.com/saintfish/chardet, but it unfortunately seems that `pkgdoc.org` has been remade into a link farm, peddling links for products to rid dogs of fleas and humans of unwanted extra pounds. The documentation for this library and others sadly seems to have gone missing on that site.

A little sample of the computer-generated haiku I found when I visited:

> Flexpet For Dogs In Maine,ME
> proper enzymes to
> digest it anyway.Feeding your pet
> Just like you or I,
> incredibly
> playful since he once was. This
> ...

**Comment by AlbinoDrought** [comment]
Not sure what was in the original doc link, but this one works for normal godoc: https://godoc.org/github.com/saintfish/chardet

**Comment by abitrolly** [comment]
@tillberg this is fixed in [5e3ef4b](https://github.com/saintfish/chardet/commit/5e3ef4b5456d970814525f09c1f176294f1751a9). Close the bug?
